//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package types

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *API) DeepCopyInto(out *API) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new API.
func (in *API) DeepCopy() *API { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdGuardInstance) DeepCopyInto(out *AdGuardInstance) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdGuardInstance.
func (in *AdGuardInstance) DeepCopy() *AdGuardInstance { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCP) DeepCopyInto(out *DHCP) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCP.
	return
}

func (in *DHCP) DeepCopy() *DHCP { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS) DeepCopyInto(out *DNS) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS.
	return
}

func (in *DNS) DeepCopy() *DNS { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Features) DeepCopyInto(out *Features) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Features.
func (in *Features) DeepCopy() *Features { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallConfig) DeepCopyInto(out *InstallConfig) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallConfig.
func (in *InstallConfig) DeepCopy() *InstallConfig { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPort) DeepCopyInto(out *InstallPort) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPort.
	return
}

func (in *InstallPort) DeepCopy() *InstallPort { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metrics) DeepCopyInto(out *Metrics) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metrics.
	return
}

func (in *Metrics) DeepCopy() *Metrics { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Protection) DeepCopyInto(out *Protection) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Protection.
	return
}

func (in *Protection) DeepCopy() *Protection { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
	return
}

func (in *TLS) DeepCopy() *TLS { _ = "STUB: not implemented"; return nil }
