//go:build !ignore_autogenerated

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bakito/adguardhome-sync/internal/client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package client -build_constraint !ignore_autogenerated -destination internal/mocks/client/zz_generated.mock.go github.com/bakito/adguardhome-sync/internal/client Client
//

// Package client is a generated GoMock package.
package client

import (
	model "github.com/bakito/adguardhome-sync/internal/client/model"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	_ = "STUB: not implemented"

	// AccessList mocks base method.
	return nil
}

func (m *MockClient) AccessList() (*model.AccessList, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AccessList indicates an expected call of AccessList.
func (mr *MockClientMockRecorder) AccessList() *gomock.Call { _ = "STUB: not implemented"; return nil }

// AddClient mocks base method.
func (m *MockClient) AddClient(client *model.Client) error { _ = "STUB: not implemented"; return nil }

// AddClient indicates an expected call of AddClient.
func (mr *MockClientMockRecorder) AddClient(client any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddDHCPStaticLease mocks base method.
func (m *MockClient) AddDHCPStaticLease(lease model.DhcpStaticLease) error {
	_ = "STUB: not implemented"
	return nil
}

// AddDHCPStaticLease indicates an expected call of AddDHCPStaticLease.
func (mr *MockClientMockRecorder) AddDHCPStaticLease(lease any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddFilter mocks base method.
func (m *MockClient) AddFilter(whitelist bool, f model.Filter) error {
	_ = "STUB: not implemented"
	return nil
}

// AddFilter indicates an expected call of AddFilter.
func (mr *MockClientMockRecorder) AddFilter(whitelist, f any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddRewriteEntries mocks base method.
func (m *MockClient) AddRewriteEntries(e ...model.RewriteEntry) error {
	_ = "STUB: not implemented"
	return nil
}

// AddRewriteEntries indicates an expected call of AddRewriteEntries.
func (mr *MockClientMockRecorder) AddRewriteEntries(e ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BlockedServicesSchedule mocks base method.
func (m *MockClient) BlockedServicesSchedule() (*model.BlockedServicesSchedule, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BlockedServicesSchedule indicates an expected call of BlockedServicesSchedule.
func (mr *MockClientMockRecorder) BlockedServicesSchedule() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Clients mocks base method.
func (m *MockClient) Clients() (*model.Clients, error) { _ = "STUB: not implemented"; return nil, nil }

// Clients indicates an expected call of Clients.
func (mr *MockClientMockRecorder) Clients() *gomock.Call { _ = "STUB: not implemented"; return nil }

// DNSConfig mocks base method.
func (m *MockClient) DNSConfig() (*model.DNSConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DNSConfig indicates an expected call of DNSConfig.
func (mr *MockClientMockRecorder) DNSConfig() *gomock.Call { _ = "STUB: not implemented"; return nil }

// DeleteClient mocks base method.
func (m *MockClient) DeleteClient(client *model.Client) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockClientMockRecorder) DeleteClient(client any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteDHCPStaticLease mocks base method.
func (m *MockClient) DeleteDHCPStaticLease(lease model.DhcpStaticLease) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteDHCPStaticLease indicates an expected call of DeleteDHCPStaticLease.
func (mr *MockClientMockRecorder) DeleteDHCPStaticLease(lease any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteFilter mocks base method.
func (m *MockClient) DeleteFilter(whitelist bool, f model.Filter) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteFilter indicates an expected call of DeleteFilter.
func (mr *MockClientMockRecorder) DeleteFilter(whitelist, f any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRewriteEntries mocks base method.
func (m *MockClient) DeleteRewriteEntries(e ...model.RewriteEntry) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteRewriteEntries indicates an expected call of DeleteRewriteEntries.
func (mr *MockClientMockRecorder) DeleteRewriteEntries(e ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DhcpConfig mocks base method.
func (m *MockClient) DhcpConfig() (*model.DhcpStatus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DhcpConfig indicates an expected call of DhcpConfig.
func (mr *MockClientMockRecorder) DhcpConfig() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Filtering mocks base method.
func (m *MockClient) Filtering() (*model.FilterStatus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Filtering indicates an expected call of Filtering.
func (mr *MockClientMockRecorder) Filtering() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Host mocks base method.
func (m *MockClient) Host() string { _ = "STUB: not implemented"; return "" }

// Host indicates an expected call of Host.
func (mr *MockClientMockRecorder) Host() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Parental mocks base method.
func (m *MockClient) Parental() (bool, error) { _ = "STUB: not implemented"; return false, nil }

// Parental indicates an expected call of Parental.
func (mr *MockClientMockRecorder) Parental() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ProfileInfo mocks base method.
func (m *MockClient) ProfileInfo() (*model.ProfileInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ProfileInfo indicates an expected call of ProfileInfo.
func (mr *MockClientMockRecorder) ProfileInfo() *gomock.Call { _ = "STUB: not implemented"; return nil }

// QueryLog mocks base method.
func (m *MockClient) QueryLog(limit int) (*model.QueryLog, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryLog indicates an expected call of QueryLog.
func (mr *MockClientMockRecorder) QueryLog(limit any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryLogConfig mocks base method.
func (m *MockClient) QueryLogConfig() (*model.QueryLogConfigWithIgnored, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryLogConfig indicates an expected call of QueryLogConfig.
func (mr *MockClientMockRecorder) QueryLogConfig() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RefreshFilters mocks base method.
func (m *MockClient) RefreshFilters(whitelist bool) error { _ = "STUB: not implemented"; return nil }

// RefreshFilters indicates an expected call of RefreshFilters.
func (mr *MockClientMockRecorder) RefreshFilters(whitelist any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RewriteList mocks base method.
func (m *MockClient) RewriteList() (*model.RewriteEntries, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RewriteList indicates an expected call of RewriteList.
func (mr *MockClientMockRecorder) RewriteList() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SafeBrowsing mocks base method.
func (m *MockClient) SafeBrowsing() (bool, error) { _ = "STUB: not implemented"; return false, nil }

// SafeBrowsing indicates an expected call of SafeBrowsing.
func (mr *MockClientMockRecorder) SafeBrowsing() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SafeSearchConfig mocks base method.
func (m *MockClient) SafeSearchConfig() (*model.SafeSearchConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SafeSearchConfig indicates an expected call of SafeSearchConfig.
func (mr *MockClientMockRecorder) SafeSearchConfig() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetAccessList mocks base method.
func (m *MockClient) SetAccessList(accessList *model.AccessList) error {
	_ = "STUB: not implemented"
	return nil
}

// SetAccessList indicates an expected call of SetAccessList.
func (mr *MockClientMockRecorder) SetAccessList(accessList any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetBlockedServicesSchedule mocks base method.
func (m *MockClient) SetBlockedServicesSchedule(schedule *model.BlockedServicesSchedule) error {
	_ = "STUB: not implemented"
	return nil
}

// SetBlockedServicesSchedule indicates an expected call of SetBlockedServicesSchedule.
func (mr *MockClientMockRecorder) SetBlockedServicesSchedule(schedule any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetCustomRules mocks base method.
func (m *MockClient) SetCustomRules(rules *[]string) error { _ = "STUB: not implemented"; return nil }

// SetCustomRules indicates an expected call of SetCustomRules.
func (mr *MockClientMockRecorder) SetCustomRules(rules any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDNSConfig mocks base method.
func (m *MockClient) SetDNSConfig(config *model.DNSConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// SetDNSConfig indicates an expected call of SetDNSConfig.
func (mr *MockClientMockRecorder) SetDNSConfig(config any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDhcpConfig mocks base method.
func (m *MockClient) SetDhcpConfig(status *model.DhcpStatus) error {
	_ = "STUB: not implemented"
	return nil
}

// SetDhcpConfig indicates an expected call of SetDhcpConfig.
func (mr *MockClientMockRecorder) SetDhcpConfig(status any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetProfileInfo mocks base method.
func (m *MockClient) SetProfileInfo(settings *model.ProfileInfo) error {
	_ = "STUB: not implemented"
	return nil
}

// SetProfileInfo indicates an expected call of SetProfileInfo.
func (mr *MockClientMockRecorder) SetProfileInfo(settings any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetQueryLogConfig mocks base method.
func (m *MockClient) SetQueryLogConfig(ql *model.QueryLogConfigWithIgnored) error {
	_ = "STUB: not implemented"
	return nil
}

// SetQueryLogConfig indicates an expected call of SetQueryLogConfig.
func (mr *MockClientMockRecorder) SetQueryLogConfig(ql any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetSafeSearchConfig mocks base method.
func (m *MockClient) SetSafeSearchConfig(settings *model.SafeSearchConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// SetSafeSearchConfig indicates an expected call of SetSafeSearchConfig.
func (mr *MockClientMockRecorder) SetSafeSearchConfig(settings any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetStatsConfig mocks base method.
func (m *MockClient) SetStatsConfig(sc *model.PutStatsConfigUpdateRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// SetStatsConfig indicates an expected call of SetStatsConfig.
func (mr *MockClientMockRecorder) SetStatsConfig(sc any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTLSConfig mocks base method.
func (m *MockClient) SetTLSConfig(tls *model.TlsConfig) error {
	_ = "STUB: not implemented"
	return nil
}

// SetTLSConfig indicates an expected call of SetTLSConfig.
func (mr *MockClientMockRecorder) SetTLSConfig(tls any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Setup mocks base method.
func (m *MockClient) Setup() error { _ = "STUB: not implemented"; return nil }

// Setup indicates an expected call of Setup.
func (mr *MockClientMockRecorder) Setup() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stats mocks base method.
func (m *MockClient) Stats() (*model.Stats, error) { _ = "STUB: not implemented"; return nil, nil }

// Stats indicates an expected call of Stats.
func (mr *MockClientMockRecorder) Stats() *gomock.Call { _ = "STUB: not implemented"; return nil }

// StatsConfig mocks base method.
func (m *MockClient) StatsConfig() (*model.GetStatsConfigResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StatsConfig indicates an expected call of StatsConfig.
func (mr *MockClientMockRecorder) StatsConfig() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Status mocks base method.
func (m *MockClient) Status() (*model.ServerStatus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Status indicates an expected call of Status.
func (mr *MockClientMockRecorder) Status() *gomock.Call { _ = "STUB: not implemented"; return nil }

// TLSConfig mocks base method.
func (m *MockClient) TLSConfig() (*model.TlsConfig, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TLSConfig indicates an expected call of TLSConfig.
func (mr *MockClientMockRecorder) TLSConfig() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ToggleFiltering mocks base method.
func (m *MockClient) ToggleFiltering(enabled bool, interval int) error {
	_ = "STUB: not implemented"
	return nil
}

// ToggleFiltering indicates an expected call of ToggleFiltering.
func (mr *MockClientMockRecorder) ToggleFiltering(enabled, interval any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ToggleParental mocks base method.
func (m *MockClient) ToggleParental(enable bool) error { _ = "STUB: not implemented"; return nil }

// ToggleParental indicates an expected call of ToggleParental.
func (mr *MockClientMockRecorder) ToggleParental(enable any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ToggleProtection mocks base method.
func (m *MockClient) ToggleProtection(enable bool) error { _ = "STUB: not implemented"; return nil }

// ToggleProtection indicates an expected call of ToggleProtection.
func (mr *MockClientMockRecorder) ToggleProtection(enable any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ToggleSafeBrowsing mocks base method.
func (m *MockClient) ToggleSafeBrowsing(enable bool) error { _ = "STUB: not implemented"; return nil }

// ToggleSafeBrowsing indicates an expected call of ToggleSafeBrowsing.
func (mr *MockClientMockRecorder) ToggleSafeBrowsing(enable any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateClient mocks base method.
func (m *MockClient) UpdateClient(client *model.Client) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockClientMockRecorder) UpdateClient(client any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateFilter mocks base method.
func (m *MockClient) UpdateFilter(whitelist bool, f model.Filter) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateFilter indicates an expected call of UpdateFilter.
func (mr *MockClientMockRecorder) UpdateFilter(whitelist, f any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRewriteEntries mocks base method.
func (m *MockClient) UpdateRewriteEntries(e ...model.RewriteUpdate) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRewriteEntries indicates an expected call of UpdateRewriteEntries.
func (mr *MockClientMockRecorder) UpdateRewriteEntries(e ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
