//go:build !ignore_autogenerated

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bakito/adguardhome-sync/internal/config (interfaces: Flags)
//
// Generated by this command:
//
//	mockgen -package client -build_constraint !ignore_autogenerated -destination internal/mocks/flags/zz_generated.mock.go github.com/bakito/adguardhome-sync/internal/config Flags
//

// Package client is a generated GoMock package.
package client

import (
	gomock "go.uber.org/mock/gomock"
)

// MockFlags is a mock of Flags interface.
type MockFlags struct {
	ctrl     *gomock.Controller
	recorder *MockFlagsMockRecorder
	isgomock struct{}
}

// MockFlagsMockRecorder is the mock recorder for MockFlags.
type MockFlagsMockRecorder struct {
	mock *MockFlags
}

// NewMockFlags creates a new mock instance.
func NewMockFlags(ctrl *gomock.Controller) *MockFlags { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlags) EXPECT() *MockFlagsMockRecorder {
	_ = "STUB: not implemented"

	// Changed mocks base method.
	return nil
}

func (m *MockFlags) Changed(name string) bool { _ = "STUB: not implemented"; return false }

// Changed indicates an expected call of Changed.
func (mr *MockFlagsMockRecorder) Changed(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBool mocks base method.
func (m *MockFlags) GetBool(name string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// GetBool indicates an expected call of GetBool.
func (mr *MockFlagsMockRecorder) GetBool(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInt mocks base method.
func (m *MockFlags) GetInt(name string) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// GetInt indicates an expected call of GetInt.
func (mr *MockFlagsMockRecorder) GetInt(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetString mocks base method.
func (m *MockFlags) GetString(name string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetString indicates an expected call of GetString.
func (mr *MockFlagsMockRecorder) GetString(name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
